spring.application.name=${APP_NAME:demo}
server.port=${APP_PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/demo_spring_angular}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=${LOGGING_LEVEL_WEB:INFO}
logging.level.org.hibernate.SQL=${LOGGING_LEVEL_HIBERNATE:DEBUG}

# Jackson Configuration
spring.jackson.default-property-inclusion=${JACKSON_DEFAULT_PROPERTY_INCLUSION:non_null}
spring.jackson.serialization.indent-output=${JACKSON_INDENT_OUTPUT:true}

server.error.include-message=${SERVER_ERROR_INCLUDE_MESSAGE:always}
server.error.include-binding-errors=${SERVER_ERROR_INCLUDE_BINDING_ERRORS:always}